INSERT INTO "Product" ("id", "slug", "name", "category", "tagline", "description", "ingredients", "allergens", "netWeight", "priceCents", "stockQty", "status", "accentColor", "createdAt", "updatedAt") VALUES
('prod_blue_raspberry', 'blue-raspberry-blast', 'Blue Raspberry Blast', 'SOUR', 'Electric blue raspberry with a puckery finish', 'Electric blue raspberry with a puckery finish', 'See product label for current ingredients.', ARRAY['Made in a shared facility'], '8 oz (227g)', 800, 24, 'ACTIVE', '#2EC5FF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_rainbow_sour', 'rainbow-sour-mix', 'Rainbow Sour Mix', 'SOUR', 'Belts, rings and drops with maximum zing', 'Belts, rings and drops with maximum zing', 'See product label for current ingredients.', ARRAY['Made in a shared facility'], '8 oz (227g)', 800, 24, 'ACTIVE', '#EA537B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_chamoy_heatwave', 'chamoy-heatwave', 'Chamoy Heatwave', 'SPICY', 'Sweet fruit gummies with a chili-lime kick', 'Sweet fruit gummies with a chili-lime kick', 'See product label for current ingredients.', ARRAY['Made in a shared facility'], '8 oz (227g)', 1199, 18, 'ACTIVE', '#FFD23F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_brownie_brittle', 'brownie-brittle', 'Brownie Brittle', 'BRITTLE', 'Thin, crispy and loaded with chocolate', 'Thin, crispy and loaded with chocolate', 'See product label for current ingredients.', ARRAY['Made in a shared facility'], '8 oz (227g)', 1200, 18, 'ACTIVE', '#B5622A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_gummy_party', 'gummy-bear-party', 'Gummy Bear Party', 'GUMMIES', 'Classic fruit gummies in every happy color', 'Classic fruit gummies in every happy color', 'See product label for current ingredients.', ARRAY['Made in a shared facility'], '8 oz (227g)', 699, 24, 'ACTIVE', '#9BDB4D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_oozie_drops', 'sour-oozie-drops', 'Sour Oozie Drops', 'SOUR', 'Soft-centered drops dusted with sour sparkle', 'Soft-centered drops dusted with sour sparkle', 'See product label for current ingredients.', ARRAY['Made in a shared facility'], '8 oz (227g)', 1099, 20, 'ACTIVE', '#6B1749', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_chocolate_bark', 'chocolate-crunch-bark', 'Chocolate Crunch Bark', 'BARK', 'Deep chocolate, crispy bits and big crunch', 'Deep chocolate, crispy bits and big crunch', 'See product label for current ingredients.', ARRAY['Made in a shared facility'], '8 oz (227g)', 1599, 16, 'ACTIVE', '#FFF2D9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('prod_spicy_bears', 'spicy-gummy-bears', 'Spicy Gummy Bears', 'SPICY', 'Juicy bears tossed in chamoy and chili', 'Juicy bears tossed in chamoy and chili', 'See product label for current ingredients.', ARRAY['Made in a shared facility'], '8 oz (227g)', 999, 20, 'ACTIVE', '#F08245', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO UPDATE SET "name" = EXCLUDED."name", "category" = EXCLUDED."category", "tagline" = EXCLUDED."tagline", "description" = EXCLUDED."description", "priceCents" = EXCLUDED."priceCents", "stockQty" = EXCLUDED."stockQty", "status" = EXCLUDED."status", "accentColor" = EXCLUDED."accentColor", "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "ProductImage" ("id", "productId", "storagePath", "url", "alt", "position", "createdAt") VALUES
('img_blue_raspberry', 'prod_blue_raspberry', '/generated/blue-sour-cutout.png', '/generated/blue-sour-cutout.png', 'Blue Raspberry Blast', 0, CURRENT_TIMESTAMP),
('img_rainbow_sour', 'prod_rainbow_sour', '/generated/rainbow-sour-cutout.png', '/generated/rainbow-sour-cutout.png', 'Rainbow Sour Mix', 0, CURRENT_TIMESTAMP),
('img_chamoy_heatwave', 'prod_chamoy_heatwave', '/generated/chamoy-cutout.png', '/generated/chamoy-cutout.png', 'Chamoy Heatwave', 0, CURRENT_TIMESTAMP),
('img_brownie_brittle', 'prod_brownie_brittle', '/generated/brittle-cutout.png', '/generated/brittle-cutout.png', 'Brownie Brittle', 0, CURRENT_TIMESTAMP),
('img_gummy_party', 'prod_gummy_party', '/generated/rainbow-sour-cutout.png', '/generated/rainbow-sour-cutout.png', 'Gummy Bear Party', 0, CURRENT_TIMESTAMP),
('img_oozie_drops', 'prod_oozie_drops', '/generated/blue-sour-cutout.png', '/generated/blue-sour-cutout.png', 'Sour Oozie Drops', 0, CURRENT_TIMESTAMP),
('img_chocolate_bark', 'prod_chocolate_bark', '/generated/brittle-cutout.png', '/generated/brittle-cutout.png', 'Chocolate Crunch Bark', 0, CURRENT_TIMESTAMP),
('img_spicy_bears', 'prod_spicy_bears', '/generated/chamoy-cutout.png', '/generated/chamoy-cutout.png', 'Spicy Gummy Bears', 0, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO UPDATE SET "url" = EXCLUDED."url", "storagePath" = EXCLUDED."storagePath", "alt" = EXCLUDED."alt";
