import { InfoPage, InfoSection } from '@/components/info-page';

export const metadata = { title: 'Shipping & Returns | CandyRama' };
export default function ShippingPage(){return <InfoPage eyebrow="THE SWEET DETAILS" title="Shipping & returns" intro="How we get your candy there fresh—and what happens when something goes sideways.">
  <InfoSection title="Packing and delivery"><h3>Processing time</h3><p>Orders are packed within 1–2 business days. Orders placed before noon on a business day may ship the same day. We do not process orders on weekends or major holidays.</p><div className="shipping-table"><div><b>Standard</b><span>3–5 business days</span><span>Calculated at checkout</span></div><div><b>Expedited</b><span>2–3 business days</span><span>Calculated at checkout</span></div><div><b>Express</b><span>1–2 business days</span><span>Calculated at checkout</span></div><div><b>Free shipping</b><span>3–5 business days</span><span>Orders over $50</span></div></div><p className="fine-print">Delivery estimates begin after processing and may change during holidays, severe weather, or carrier disruptions.</p></InfoSection>
  <InfoSection title="Warm-weather orders"><p>Chocolate bark, caramel brittle, and some gummies are heat-sensitive. During warm weather, choose expedited delivery when possible and arrange to bring the package inside promptly. Candy left on a hot porch may soften or melt.</p><p>Need help choosing a shipping method? Email <a href="mailto:customercare@twistedtreatz.com">customercare@twistedtreatz.com</a> before ordering.</p></InfoSection>
  <InfoSection title="Problems with an order"><p>If an item arrives damaged, missing, or incorrect, contact us within 48 hours of delivery. Include your order number, a clear photo, and a short description. We’ll review the issue within 1–2 business days and determine whether a replacement, store credit, or refund is appropriate.</p></InfoSection>
  <InfoSection title="Returns and refunds"><p>Opened or consumed food items cannot be returned. Unopened, non-perishable merchandise may be eligible for return within seven days of delivery when it remains sealed in its original packaging. Contact customer care before mailing anything back.</p><p>Original shipping charges are non-refundable. Customers cover return shipping unless the return resulted from our mistake. Approved refunds are sent to the original payment method within 5–7 business days after inspection.</p></InfoSection>
  <InfoSection title="Missing packages"><p>If tracking shows “delivered,” check with household members, neighbors, and the local carrier first. If the package is still missing, contact us and we’ll help investigate. CandyRama cannot guarantee replacement of packages confirmed delivered by the carrier.</p></InfoSection>
  </InfoPage>}
