'use client';
import { useEffect,useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { Download,Upload } from 'lucide-react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

export function AdminCatalogClient(){
  const [session,setSession]=useState<Session|null>(null);const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{const supabase=getSupabaseBrowser();void supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>data.subscription.unsubscribe();},[]);
  async function signIn(){setBusy(true);setMessage('');const {error}=await getSupabaseBrowser().auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:`${location.origin}/admin/catalog`}});setMessage(error?error.message:'Check your email for the secure sign-in link.');setBusy(false);}
  async function authorizedFetch(url:string,init?:RequestInit){const token=session?.access_token;if(!token)throw new Error('Your admin session expired.');const headers=new Headers(init?.headers);headers.set('Authorization',`Bearer ${token}`);return fetch(url,{...init,headers});}
  async function download(){setBusy(true);setMessage('');try{const response=await authorizedFetch('/api/v1/admin/products/workbook');if(!response.ok)throw new Error((await response.json()).error);const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='CandyRama-Product-Catalog.xlsx';anchor.click();URL.revokeObjectURL(url);setMessage('Current product workbook downloaded.');}catch(error){setMessage(error instanceof Error?error.message:'Download failed.');}setBusy(false);}
  async function upload(file:File){setBusy(true);setMessage('');try{const body=new FormData();body.set('file',file);const response=await authorizedFetch('/api/v1/admin/products/workbook',{method:'POST',body});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage(`Import complete: ${result.data.created} created and ${result.data.updated} updated.`);}catch(error){setMessage(error instanceof Error?error.message:'Import failed.');}setBusy(false);}
  if(!session)return <main className="admin-shell"><section className="admin-card"><p className="eyebrow">CANDYRAMA ADMIN</p><h1>Catalog sign in</h1><p>Use an invited administrator email. We’ll send a one-time secure link.</p><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="admin@candyrama.com"/></label><button className="button primary" disabled={busy||!email} onClick={signIn}>{busy?'Sending…':'Email sign-in link'}</button>{message&&<output className="admin-message">{message}</output>}</section></main>;
  return <main className="admin-shell"><section className="admin-card wide"><p className="eyebrow">CANDYRAMA ADMIN</p><h1>Product catalog</h1><p>Download the current catalog, edit it in Excel, then upload the same workbook. Imports are validated and recorded in the audit log.</p><div className="admin-actions"><button className="button secondary" disabled={busy} onClick={download}><Download/> Download products</button><label className={`button primary${busy?' disabled':''}`}><Upload/> Upload edited workbook<input type="file" accept=".xlsx" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);event.target.value='';}}/></label></div><div className="admin-note"><strong>Images stay separate.</strong><p>Attach product images in your CandyRama chat. They can be cleaned, approved, and uploaded without risking spreadsheet links or accidental image replacement.</p></div>{message&&<output className="admin-message">{message}</output>}<button className="text-link" onClick={()=>void getSupabaseBrowser().auth.signOut()}>Sign out</button></section></main>;
}
