import { InfoPage, InfoSection } from '@/components/info-page';

export const metadata = { title: 'Privacy Policy | CandyRama' };
export default function PrivacyPage(){return <InfoPage eyebrow="YOUR DATA, RESPECTED" title="Privacy policy" intro="What CandyRama collects, why we need it, and what choices you have. Last updated September 5, 2026.">
  <InfoSection title="Information we collect"><p>We collect the information needed to process orders and support customers, including your name, billing and shipping addresses, email, phone number, order details, and messages you send us. Device, browser, cookie, and site usage information may also be collected automatically.</p><p>Our payment processor handles payment card details. CandyRama does not store them directly.</p></InfoSection>
  <InfoSection title="How we use information"><ul><li>Process, fulfill, and deliver orders</li><li>Send receipts, shipping updates, and service messages</li><li>Answer questions and resolve order problems</li><li>Prevent fraud and protect the store</li><li>Improve products and the shopping experience</li><li>Send marketing only when you have opted in</li></ul><p>We do not sell personal information.</p></InfoSection>
  <InfoSection title="When information is shared"><p>Information may be shared with payment processors, shipping carriers, email providers, analytics services, and other vendors only as needed to operate the store. We may also disclose information when required by law or necessary to protect customers and the business.</p></InfoSection>
  <InfoSection title="Cookies and choices"><p>Essential cookies keep the cart and checkout working. Analytics and marketing cookies help us understand performance and may be controlled through your browser or any cookie controls provided on the site.</p></InfoSection>
  <InfoSection title="Your rights"><p>Depending on where you live, you may request access, correction, deletion, or portability of personal information and opt out of marketing. Email <a href="mailto:customercare@twistedtreatz.com">customercare@twistedtreatz.com</a>. We may keep some order records for tax, accounting, fraud prevention, or legal reasons.</p></InfoSection>
  <InfoSection title="Children and security"><p>The store is not directed to children under 13. We use reasonable safeguards to protect information, but no online service can guarantee absolute security.</p></InfoSection>
  </InfoPage>}
